language: cpp
compiler:
  - clang
  - gcc
dist: bionic
script:
  - mkdir -p build
  - cd build
  - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - ctest
